-- ============================================
-- STIGMATOR PARTNERSHIP SYSTEM
-- The "Equity Ink" Architecture
-- ============================================

-- Partnership Codes (Generated by artist for tattoo clients)
CREATE TABLE partnership_codes (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    code TEXT UNIQUE NOT NULL, -- e.g., "INK-ALEX-2024-X7K9"
    design_id UUID REFERENCES designs(id) ON DELETE CASCADE,
    artist_id UUID REFERENCES profiles(id) NOT NULL,
    
    -- Split configuration (percentages as integers, total must = 100)
    artist_split INTEGER NOT NULL DEFAULT 50, -- Artist keeps 50%
    partner_split INTEGER NOT NULL DEFAULT 20, -- Original canvas (tattoo wearer) gets 20%
    platform_split INTEGER NOT NULL DEFAULT 15, -- Stigmator takes 15%
    
    -- Status
    status TEXT NOT NULL CHECK (status IN ('active', 'redeemed', 'expired', 'revoked')) DEFAULT 'active',
    max_uses INTEGER DEFAULT 1, -- Usually 1:1 partnership, but can be multiple for flash
    uses_remaining INTEGER DEFAULT 1,
    
    -- Metadata
    description TEXT, -- e.g., "Full back piece - Dragon - Sarah M."
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    redeemed_at TIMESTAMPTZ,
    redeemed_by UUID REFERENCES profiles(id),
    
    -- Validation
    CONSTRAINT valid_splits CHECK (artist_split + partner_split + platform_split = 100),
    CONSTRAINT positive_splits CHECK (artist_split >= 0 AND partner_split >= 0 AND platform_split >= 0)
);

-- User Design Partnerships (When someone redeems a code)
CREATE TABLE design_partnerships (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    partnership_code_id UUID REFERENCES partnership_codes(id) NOT NULL,
    design_id UUID REFERENCES designs(id) NOT NULL,
    artist_id UUID REFERENCES profiles(id) NOT NULL,
    partner_id UUID REFERENCES profiles(id) NOT NULL, -- The tattoo wearer
    
    -- Their agreed split
    partner_split INTEGER NOT NULL,
    artist_split INTEGER NOT NULL,
    
    -- Verification
    verification_status TEXT NOT NULL CHECK (verification_status IN ('pending', 'verified', 'rejected')) DEFAULT 'pending',
    verification_photo_url TEXT, -- Photo of the actual tattoo
    verified_at TIMESTAMPTZ,
    
    -- Earnings tracking
    total_earnings INTEGER DEFAULT 0, -- In cents
    lifetime_sales INTEGER DEFAULT 0,
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(design_id, partner_id) -- One partnership per design per person
);

-- Partnership Earnings (Detailed transaction log)
CREATE TABLE partnership_earnings (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    design_partnership_id UUID REFERENCES design_partnerships(id) NOT NULL,
    order_item_id UUID REFERENCES order_items(id) NOT NULL,
    
    -- Who got what
    artist_id UUID REFERENCES profiles(id) NOT NULL,
    partner_id UUID REFERENCES profiles(id) NOT NULL,
    
    -- Amounts in cents
    sale_amount INTEGER NOT NULL,
    artist_earnings INTEGER NOT NULL,
    partner_earnings INTEGER NOT NULL,
    platform_earnings INTEGER NOT NULL,
    
    -- Status
    paid_to_artist BOOLEAN DEFAULT FALSE,
    paid_to_partner BOOLEAN DEFAULT FALSE,
    artist_payout_id UUID REFERENCES payouts(id),
    partner_payout_id UUID REFERENCES payouts(id),
    
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Design Ownership Structure (Tracks all partners for a design)
CREATE TABLE design_ownership (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    design_id UUID REFERENCES designs(id) NOT NULL,
    artist_id UUID REFERENCES profiles(id) NOT NULL,
    
    -- How many partners does this design have?
    partner_count INTEGER DEFAULT 0,
    
    -- Total earnings across all partnerships
    total_partner_earnings INTEGER DEFAULT 0,
    total_artist_earnings INTEGER DEFAULT 0,
    
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(design_id)
);

-- Indexes for performance
CREATE INDEX idx_partnership_codes_code ON partnership_codes(code);
CREATE INDEX idx_partnership_codes_design ON partnership_codes(design_id);
CREATE INDEX idx_partnership_codes_status ON partnership_codes(status);
CREATE INDEX idx_design_partnerships_partner ON design_partnerships(partner_id);
CREATE INDEX idx_design_partnerships_design ON design_partnerships(design_id);
CREATE INDEX idx_partnership_earnings_partner ON partnership_earnings(partner_id);
CREATE INDEX idx_partnership_earnings_artist ON partnership_earnings(artist_id);

-- Triggers

-- Auto-generate unique code
CREATE OR REPLACE FUNCTION generate_partnership_code()
RETURNS TRIGGER AS $$
BEGIN
    NEW.code = 'INK-' || UPPER(SUBSTRING(MD5(NEW.id::TEXT), 1, 8));
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SET search_path = 'public';

CREATE TRIGGER set_partnership_code BEFORE INSERT ON partnership_codes
    FOR EACH ROW EXECUTE FUNCTION generate_partnership_code();

-- Update design ownership stats when partnership created
CREATE OR REPLACE FUNCTION update_design_ownership()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO design_ownership (design_id, artist_id, partner_count)
    VALUES (NEW.design_id, NEW.artist_id, 1)
    ON CONFLICT (design_id) 
    DO UPDATE SET 
        partner_count = design_ownership.partner_count + 1,
        updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SET search_path = 'public';

CREATE TRIGGER update_ownership_on_partnership 
    AFTER INSERT ON design_partnerships
    FOR EACH ROW EXECUTE FUNCTION update_design_ownership();

-- RLS Policies
ALTER TABLE partnership_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE design_partnerships ENABLE ROW LEVEL SECURITY;
ALTER TABLE partnership_earnings ENABLE ROW LEVEL SECURITY;
ALTER TABLE design_ownership ENABLE ROW LEVEL SECURITY;

-- Artists can manage their own codes
CREATE POLICY "Artists can manage their codes" 
ON partnership_codes FOR ALL USING (auth.uid() = artist_id);

-- Partners can view their own partnerships
CREATE POLICY "Partners can view their partnerships" 
ON design_partnerships FOR SELECT USING (auth.uid() = partner_id OR auth.uid() = artist_id);

-- Partners can view their earnings
CREATE POLICY "Partners can view their earnings" 
ON partnership_earnings FOR SELECT USING (auth.uid() = partner_id OR auth.uid() = artist_id);
