-- ============================================
-- STIGMATOR: ENHANCED PARTNERSHIP SYSTEM
-- Multi-Design Garment Support
-- ============================================

-- Partnership Codes (Generated by artist for tattoo clients)
-- This is SEPARATE from garment uploads - it's the pre-arrangement
CREATE TABLE partnership_codes (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    code TEXT UNIQUE NOT NULL, -- e.g., "INK-ALEX-2024-X7K9"
    design_id UUID REFERENCES designs(id) ON DELETE CASCADE NOT NULL,
    artist_id UUID REFERENCES profiles(id) NOT NULL,
    studio_id UUID REFERENCES studios(id), -- Optional: linked studio
    
    -- Split configuration (percentages as integers, total must = 100)
    -- These splits are from the ARTIST'S SHARE only
    -- Platform takes 15% at garment level, these splits happen from remaining 85%
    artist_share INTEGER NOT NULL DEFAULT 50, -- Artist keeps this % of their earnings
    client_share INTEGER NOT NULL DEFAULT 20, -- Client (tattoo wearer) gets this %
    studio_share INTEGER NOT NULL DEFAULT 0,  -- Studio gets this % (optional)
    
    -- Validation: artist_share + client_share + studio_share = 100
    
    -- Status
    status TEXT NOT NULL CHECK (status IN ('active', 'redeemed', 'expired', 'revoked')) DEFAULT 'active',
    max_uses INTEGER DEFAULT 1, -- Usually 1:1 partnership, but can be multiple for flash
    uses_remaining INTEGER DEFAULT 1,
    
    -- Client info (filled when code is created, confirmed when redeemed)
    intended_client_name TEXT,
    intended_client_email TEXT,
    tattoo_location TEXT, -- e.g., "LEFT FOREARM", "FULL BACK"
    session_date DATE,
    notes TEXT,
    
    -- Timestamps
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    redeemed_at TIMESTAMPTZ,
    redeemed_by UUID REFERENCES profiles(id),
    
    -- Validation constraint
    CONSTRAINT valid_partnership_splits CHECK (artist_share + client_share + studio_share = 100),
    CONSTRAINT positive_partnership_splits CHECK (artist_share >= 0 AND client_share >= 0 AND studio_share >= 0)
);

-- User Design Partnerships (When someone redeems a code)
CREATE TABLE design_partnerships (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    partnership_code_id UUID REFERENCES partnership_codes(id) NOT NULL,
    design_id UUID REFERENCES designs(id) NOT NULL,
    artist_id UUID REFERENCES profiles(id) NOT NULL,
    partner_id UUID REFERENCES profiles(id) NOT NULL, -- The tattoo wearer (client)
    studio_id UUID REFERENCES studios(id), -- If studio is involved
    
    -- Their agreed split (copied from code at redemption)
    artist_share INTEGER NOT NULL,
    client_share INTEGER NOT NULL,
    studio_share INTEGER NOT NULL,
    
    -- Verification
    verification_status TEXT NOT NULL CHECK (verification_status IN ('pending', 'verified', 'rejected')) DEFAULT 'pending',
    verification_photo_url TEXT, -- Photo of the actual tattoo
    verified_at TIMESTAMPTZ,
    verified_by UUID REFERENCES profiles(id),
    
    -- Earnings tracking (from this specific partnership)
    total_earnings INTEGER DEFAULT 0, -- In cents
    lifetime_sales INTEGER DEFAULT 0,
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(design_id, partner_id) -- One partnership per design per person
);

-- GARMENT-LEVEL PARTNERSHIPS
-- This is where the magic happens for multi-design garments

-- A garment can have multiple designs from different artists
-- Each design can have multiple partners
-- All splits must be tracked

CREATE TABLE garment_design_partnerships (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    
    -- Links
    product_design_id UUID REFERENCES product_designs(id) NOT NULL, -- The garment with design applied
    design_partnership_id UUID REFERENCES design_partnerships(id) NOT NULL, -- The specific partner
    
    -- The split percentages (copied at time of garment creation to prevent changes)
    artist_share INTEGER NOT NULL,
    client_share INTEGER NOT NULL,
    studio_share INTEGER NOT NULL,
    
    -- Calculated earnings for this specific garment
    total_garment_earnings INTEGER DEFAULT 0,
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(product_design_id, design_partnership_id)
);

-- EARNINGS BREAKDOWN
-- Every sale must track exactly who gets what

CREATE TABLE earnings_breakdown (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    order_item_id UUID REFERENCES order_items(id) NOT NULL,
    
    -- Sale info
    sale_amount INTEGER NOT NULL, -- Total sale price in cents
    platform_fee INTEGER NOT NULL, -- 15% of sale
    remaining_amount INTEGER NOT NULL, -- 70% to distribute
    
    -- For single-design garments, simple split
    -- For multi-design garments, each design gets proportional share
    
    -- Who gets paid
    recipient_id UUID REFERENCES profiles(id) NOT NULL,
    recipient_type TEXT NOT NULL CHECK (recipient_type IN ('artist', 'client', 'studio', 'platform')),
    
    -- Their share of this specific sale
    amount INTEGER NOT NULL,
    percentage DECIMAL(5,2) NOT NULL, -- What % of remaining_amount they got
    
    -- Which design this earning is for (if multi-design)
    design_id UUID REFERENCES designs(id),
    
    -- Status
    paid BOOLEAN DEFAULT FALSE,
    paid_at TIMESTAMPTZ,
    payout_id UUID REFERENCES payouts(id),
    
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- MULTI-DESIGN GARMENT TRACKING
-- When a garment has designs from multiple artists

CREATE TABLE garment_designs (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    product_design_id UUID REFERENCES product_designs(id) NOT NULL, -- The garment
    design_id UUID REFERENCES designs(id) NOT NULL, -- Individual design
    artist_id UUID REFERENCES profiles(id) NOT NULL,
    
    -- Placement info
    placement_area TEXT, -- e.g., "left_sleeve", "back_panel"
    placement_order INTEGER DEFAULT 0, -- Layering order
    
    -- Revenue share for this design on this garment
    -- If 3 designs on garment, each might get 33.33% of the 70%
    revenue_percentage DECIMAL(5,2) NOT NULL DEFAULT 100.00,
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(product_design_id, design_id)
);

-- INDICES for performance
CREATE INDEX idx_partnership_codes_code ON partnership_codes(code);
CREATE INDEX idx_partnership_codes_design ON partnership_codes(design_id);
CREATE INDEX idx_partnership_codes_status ON partnership_codes(status);
CREATE INDEX idx_design_partnerships_partner ON design_partnerships(partner_id);
CREATE INDEX idx_design_partnerships_design ON design_partnerships(design_id);
CREATE INDEX idx_garment_designs_product ON garment_designs(product_design_id);
CREATE INDEX idx_earnings_recipient ON earnings_breakdown(recipient_id);
CREATE INDEX idx_earnings_order ON earnings_breakdown(order_item_id);

-- FUNCTIONS

-- Auto-generate unique code
CREATE OR REPLACE FUNCTION generate_partnership_code()
RETURNS TRIGGER AS $$
DECLARE
    artist_initials TEXT;
    year TEXT;
    random_part TEXT;
BEGIN
    -- Get artist initials from profile
    SELECT COALESCE(SUBSTRING(UPPER(display_name), 1, 2), 'XX')
    INTO artist_initials
    FROM profiles
    WHERE id = NEW.artist_id;
    
    year := EXTRACT(YEAR FROM NOW())::TEXT;
    random_part := UPPER(SUBSTRING(MD5(NEW.id::TEXT), 1, 4));
    
    NEW.code := 'INK-' || artist_initials || year || '-' || random_part;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_partnership_code BEFORE INSERT ON partnership_codes
    FOR EACH ROW EXECUTE FUNCTION generate_partnership_code();

-- Calculate earnings for a sale with multiple partners
CREATE OR REPLACE FUNCTION calculate_garment_earnings(
    p_product_design_id UUID,
    p_sale_amount INTEGER
)
RETURNS TABLE (
    recipient_id UUID,
    recipient_type TEXT,
    amount INTEGER,
    percentage DECIMAL
) AS $$
DECLARE
    v_platform_fee INTEGER;
    v_remaining INTEGER;
    v_garment_design RECORD;
    v_partnership RECORD;
    v_design_share INTEGER;
BEGIN
    -- Platform takes 15%
    v_platform_fee := (p_sale_amount * 0.15)::INTEGER;
    v_remaining := p_sale_amount - v_platform_fee;
    
    -- Return platform fee
    RETURN QUERY SELECT 
        NULL::UUID,
        'platform'::TEXT,
        v_platform_fee,
        30.00::DECIMAL;
    
    -- Get all designs on this garment
    FOR v_garment_design IN 
        SELECT gd.*, d.artist_id
        FROM garment_designs gd
        JOIN designs d ON d.id = gd.design_id
        WHERE gd.product_design_id = p_product_design_id
    LOOP
        -- This design's share of the remaining 70%
        v_design_share := (v_remaining * (v_garment_design.revenue_percentage / 100))::INTEGER;
        
        -- Check if design has partnerships
        FOR v_partnership IN 
            SELECT dp.*, dp.artist_id as artist_user_id
            FROM garment_design_partnerships gdp
            JOIN design_partnerships dp ON dp.id = gdp.design_partnership_id
            WHERE gdp.product_design_id = p_product_design_id
            AND dp.design_id = v_garment_design.design_id
        LOOP
            -- Artist gets their share
            RETURN QUERY SELECT 
                v_partnership.artist_user_id,
                'artist'::TEXT,
                (v_design_share * (v_partnership.artist_share / 100))::INTEGER,
                (v_garment_design.revenue_percentage * (v_partnership.artist_share / 100))::DECIMAL;
            
            -- Client gets their share
            IF v_partnership.client_share > 0 THEN
                RETURN QUERY SELECT 
                    v_partnership.partner_id,
                    'client'::TEXT,
                    (v_design_share * (v_partnership.client_share / 100))::INTEGER,
                    (v_garment_design.revenue_percentage * (v_partnership.client_share / 100))::DECIMAL;
            END IF;
            
            -- Studio gets their share
            IF v_partnership.studio_share > 0 AND v_partnership.studio_id IS NOT NULL THEN
                RETURN QUERY SELECT 
                    v_partnership.studio_id,
                    'studio'::TEXT,
                    (v_design_share * (v_partnership.studio_share / 100))::INTEGER,
                    (v_garment_design.revenue_percentage * (v_partnership.studio_share / 100))::DECIMAL;
            END IF;
        END LOOP;
        
        -- If no partnerships, artist gets 100% of design share
        IF NOT EXISTS (
            SELECT 1 FROM garment_design_partnerships 
            WHERE product_design_id = p_product_design_id
            AND design_partnership_id IN (
                SELECT id FROM design_partnerships WHERE design_id = v_garment_design.design_id
            )
        ) THEN
            RETURN QUERY SELECT 
                v_garment_design.artist_id,
                'artist'::TEXT,
                v_design_share,
                v_garment_design.revenue_percentage::DECIMAL;
        END IF;
    END LOOP;
    
    RETURN;
END;
$$ LANGUAGE plpgsql;

-- RLS POLICIES
ALTER TABLE partnership_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE design_partnerships ENABLE ROW LEVEL SECURITY;
ALTER TABLE garment_design_partnerships ENABLE ROW LEVEL SECURITY;
ALTER TABLE garment_designs ENABLE ROW LEVEL SECURITY;
ALTER TABLE earnings_breakdown ENABLE ROW LEVEL SECURITY;

-- Artists can manage their own codes
CREATE POLICY "Artists manage their codes" ON partnership_codes
    FOR ALL USING (auth.uid() = artist_id);

-- Partners can view their partnerships
CREATE POLICY "Partners view their data" ON design_partnerships
    FOR SELECT USING (auth.uid() = partner_id OR auth.uid() = artist_id);

-- Earnings visible to recipients
CREATE POLICY "Recipients view earnings" ON earnings_breakdown
    FOR SELECT USING (auth.uid() = recipient_id);
