// STIGMATOR Database Schema Types for Supabase
// These types match the Prisma schema for type safety

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          email_verified: boolean;
          full_name: string | null;
          display_name: string | null;
          avatar_url: string | null;
          bio: string | null;
          location: string | null;
          website: string | null;
          instagram_handle: string | null;
          role: 'CUSTOMER' | 'ARTIST' | 'ADMIN' | 'FULFILLMENT' | 'STUDIO_MANAGER';
          is_verified: boolean;
          verification_status: 'PENDING' | 'IN_REVIEW' | 'APPROVED' | 'REJECTED' | 'SUSPENDED';
          verified_at: string | null;
          referral_code: string | null;
          referred_by_id: string | null;
          email_notifications: boolean;
          marketing_emails: boolean;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id: string;
          email: string;
          email_verified?: boolean;
          full_name?: string | null;
          display_name?: string | null;
          avatar_url?: string | null;
          bio?: string | null;
          location?: string | null;
          website?: string | null;
          instagram_handle?: string | null;
          role?: 'CUSTOMER' | 'ARTIST' | 'ADMIN' | 'FULFILLMENT' | 'STUDIO_MANAGER';
          is_verified?: boolean;
          verification_status?: 'PENDING' | 'IN_REVIEW' | 'APPROVED' | 'REJECTED' | 'SUSPENDED';
          verified_at?: string | null;
          referral_code?: string | null;
          referred_by_id?: string | null;
          email_notifications?: boolean;
          marketing_emails?: boolean;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          email?: string;
          email_verified?: boolean;
          full_name?: string | null;
          display_name?: string | null;
          avatar_url?: string | null;
          bio?: string | null;
          location?: string | null;
          website?: string | null;
          instagram_handle?: string | null;
          role?: 'CUSTOMER' | 'ARTIST' | 'ADMIN' | 'FULFILLMENT' | 'STUDIO_MANAGER';
          is_verified?: boolean;
          verification_status?: 'PENDING' | 'IN_REVIEW' | 'APPROVED' | 'REJECTED' | 'SUSPENDED';
          verified_at?: string | null;
          referral_code?: string | null;
          referred_by_id?: string | null;
          email_notifications?: boolean;
          marketing_emails?: boolean;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
      };
      artist_profiles: {
        Row: {
          id: string;
          user_id: string;
          years_experience: number | null;
          specialties: string[];
          portfolio_url: string | null;
          application_data: Json | null;
          reviewed_by_id: string | null;
          reviewed_at: string | null;
          rejection_reason: string | null;
          total_designs: number;
          total_sales: number;
          total_earnings: number;
          rating: number;
          review_count: number;
          default_splits: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          years_experience?: number | null;
          specialties?: string[];
          portfolio_url?: string | null;
          application_data?: Json | null;
          reviewed_by_id?: string | null;
          reviewed_at?: string | null;
          rejection_reason?: string | null;
          total_designs?: number;
          total_sales?: number;
          total_earnings?: number;
          rating?: number;
          review_count?: number;
          default_splits?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          years_experience?: number | null;
          specialties?: string[];
          portfolio_url?: string | null;
          application_data?: Json | null;
          reviewed_by_id?: string | null;
          reviewed_at?: string | null;
          rejection_reason?: string | null;
          total_designs?: number;
          total_sales?: number;
          total_earnings?: number;
          rating?: number;
          review_count?: number;
          default_splits?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      studios: {
        Row: {
          id: string;
          slug: string;
          name: string;
          description: string | null;
          logo_url: string | null;
          banner_url: string | null;
          address: string | null;
          city: string | null;
          state: string | null;
          country: string | null;
          postal_code: string | null;
          latitude: number | null;
          longitude: number | null;
          phone: string | null;
          email: string | null;
          website: string | null;
          instagram_handle: string | null;
          verification_status: 'PENDING' | 'IN_REVIEW' | 'APPROVED' | 'REJECTED' | 'SUSPENDED';
          verification_docs: Json | null;
          verified_at: string | null;
          artist_count: number;
          total_sales: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          description?: string | null;
          logo_url?: string | null;
          banner_url?: string | null;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          country?: string | null;
          postal_code?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          phone?: string | null;
          email?: string | null;
          website?: string | null;
          instagram_handle?: string | null;
          verification_status?: 'PENDING' | 'IN_REVIEW' | 'APPROVED' | 'REJECTED' | 'SUSPENDED';
          verification_docs?: Json | null;
          verified_at?: string | null;
          artist_count?: number;
          total_sales?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          description?: string | null;
          logo_url?: string | null;
          banner_url?: string | null;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          country?: string | null;
          postal_code?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          phone?: string | null;
          email?: string | null;
          website?: string | null;
          instagram_handle?: string | null;
          verification_status?: 'PENDING' | 'IN_REVIEW' | 'APPROVED' | 'REJECTED' | 'SUSPENDED';
          verification_docs?: Json | null;
          verified_at?: string | null;
          artist_count?: number;
          total_sales?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      designs: {
        Row: {
          id: string;
          artist_id: string;
          title: string;
          description: string | null;
          original_file: string;
          preview_image: string;
          thumbnail_image: string | null;
          status: 'DRAFT' | 'PENDING_REVIEW' | 'APPROVED' | 'REJECTED' | 'PUBLISHED' | 'ARCHIVED';
          category: string | null;
          tags: string[];
          is_nsfw: boolean;
          attribution_required: boolean;
          view_count: number;
          created_at: string;
          updated_at: string;
          published_at: string | null;
        };
        Insert: {
          id?: string;
          artist_id: string;
          title: string;
          description?: string | null;
          original_file: string;
          preview_image: string;
          thumbnail_image?: string | null;
          status?: 'DRAFT' | 'PENDING_REVIEW' | 'APPROVED' | 'REJECTED' | 'PUBLISHED' | 'ARCHIVED';
          category?: string | null;
          tags?: string[];
          is_nsfw?: boolean;
          attribution_required?: boolean;
          view_count?: number;
          created_at?: string;
          updated_at?: string;
          published_at?: string | null;
        };
        Update: {
          id?: string;
          artist_id?: string;
          title?: string;
          description?: string | null;
          original_file?: string;
          preview_image?: string;
          thumbnail_image?: string | null;
          status?: 'DRAFT' | 'PENDING_REVIEW' | 'APPROVED' | 'REJECTED' | 'PUBLISHED' | 'ARCHIVED';
          category?: string | null;
          tags?: string[];
          is_nsfw?: boolean;
          attribution_required?: boolean;
          view_count?: number;
          created_at?: string;
          updated_at?: string;
          published_at?: string | null;
        };
      };
      products: {
        Row: {
          id: string;
          artist_id: string;
          studio_id: string | null;
          name: string;
          description: string | null;
          garment_type: 'TSHIRT' | 'LONG_SLEEVE' | 'HOODIE' | 'TANK_TOP' | 'CREWNECK' | 'HAT_BEANIE' | 'HAT_TRUCKER' | 'POSTER' | 'STICKER_PACK';
          status: 'DRAFT' | 'PENDING_APPROVAL' | 'ACTIVE' | 'PAUSED' | 'SOLD_OUT' | 'ARCHIVED';
          base_price: number;
          sale_price: number | null;
          cost_to_produce: number;
          deposit_amount: number;
          deposit_recoup_enabled: boolean;
          deposit_recoup_target_sales: number;
          deposit_recouped_amount: number;
          deposit_recouped_sales_count: number;
          freshness_score: number;
          last_sale_at: string | null;
          inventory_enabled: boolean;
          inventory_count: number;
          total_sales: number;
          total_revenue: number;
          created_at: string;
          updated_at: string;
          published_at: string | null;
        };
        Insert: {
          id?: string;
          artist_id: string;
          studio_id?: string | null;
          name: string;
          description?: string | null;
          garment_type: 'TSHIRT' | 'LONG_SLEEVE' | 'HOODIE' | 'TANK_TOP' | 'CREWNECK' | 'HAT_BEANIE' | 'HAT_TRUCKER' | 'POSTER' | 'STICKER_PACK';
          status?: 'DRAFT' | 'PENDING_APPROVAL' | 'ACTIVE' | 'PAUSED' | 'SOLD_OUT' | 'ARCHIVED';
          base_price: number;
          sale_price?: number | null;
          cost_to_produce: number;
          deposit_amount?: number;
          deposit_recoup_enabled?: boolean;
          deposit_recoup_target_sales?: number;
          deposit_recouped_amount?: number;
          deposit_recouped_sales_count?: number;
          freshness_score?: number;
          last_sale_at?: string | null;
          inventory_enabled?: boolean;
          inventory_count?: number;
          total_sales?: number;
          total_revenue?: number;
          created_at?: string;
          updated_at?: string;
          published_at?: string | null;
        };
        Update: {
          id?: string;
          artist_id?: string;
          studio_id?: string | null;
          name?: string;
          description?: string | null;
          garment_type?: 'TSHIRT' | 'LONG_SLEEVE' | 'HOODIE' | 'TANK_TOP' | 'CREWNECK' | 'HAT_BEANIE' | 'HAT_TRUCKER' | 'POSTER' | 'STICKER_PACK';
          status?: 'DRAFT' | 'PENDING_APPROVAL' | 'ACTIVE' | 'PAUSED' | 'SOLD_OUT' | 'ARCHIVED';
          base_price?: number;
          sale_price?: number | null;
          cost_to_produce?: number;
          deposit_amount?: number;
          deposit_recoup_enabled?: boolean;
          deposit_recoup_target_sales?: number;
          deposit_recouped_amount?: number;
          deposit_recouped_sales_count?: number;
          freshness_score?: number;
          last_sale_at?: string | null;
          inventory_enabled?: boolean;
          inventory_count?: number;
          total_sales?: number;
          total_revenue?: number;
          created_at?: string;
          updated_at?: string;
          published_at?: string | null;
        };
      };
      product_designs: {
        Row: {
          id: string;
          product_id: string;
          design_id: string;
          position_x: number;
          position_y: number;
          scale: number;
          rotation: number;
          revenue_share: number;
          mockup_image: string;
          print_file: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          product_id: string;
          design_id: string;
          position_x?: number;
          position_y?: number;
          scale?: number;
          rotation?: number;
          revenue_share?: number;
          mockup_image: string;
          print_file?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          product_id?: string;
          design_id?: string;
          position_x?: number;
          position_y?: number;
          scale?: number;
          rotation?: number;
          revenue_share?: number;
          mockup_image?: string;
          print_file?: string | null;
          created_at?: string;
        };
      };
      partnership_codes: {
        Row: {
          id: string;
          code: string;
          artist_id: string;
          design_id: string;
          artist_share: number;
          partner_share: number;
          studio_share: number;
          status: 'GENERATED' | 'SENT' | 'REDEEMED' | 'EXPIRED' | 'REVOKED';
          expires_at: string | null;
          requires_photo: boolean;
          requires_location: boolean;
          created_at: string;
          redeemed_at: string | null;
        };
        Insert: {
          id?: string;
          code: string;
          artist_id: string;
          design_id: string;
          artist_share: number;
          partner_share: number;
          studio_share?: number;
          status?: 'GENERATED' | 'SENT' | 'REDEEMED' | 'EXPIRED' | 'REVOKED';
          expires_at?: string | null;
          requires_photo?: boolean;
          requires_location?: boolean;
          created_at?: string;
          redeemed_at?: string | null;
        };
        Update: {
          id?: string;
          code?: string;
          artist_id?: string;
          design_id?: string;
          artist_share?: number;
          partner_share?: number;
          studio_share?: number;
          status?: 'GENERATED' | 'SENT' | 'REDEEMED' | 'EXPIRED' | 'REVOKED';
          expires_at?: string | null;
          requires_photo?: boolean;
          requires_location?: boolean;
          created_at?: string;
          redeemed_at?: string | null;
        };
      };
      partnerships: {
        Row: {
          id: string;
          code_id: string;
          partner_id: string;
          artist_share: number;
          partner_share: number;
          studio_share: number;
          status: 'PENDING_VERIFICATION' | 'ACTIVE' | 'SUSPENDED' | 'TERMINATED';
          verification_photo: string | null;
          verification_location: Json | null;
          verified_at: string | null;
          total_sales: number;
          total_earnings: number;
          partner_notified: boolean;
          created_at: string;
          activated_at: string | null;
        };
        Insert: {
          id?: string;
          code_id: string;
          partner_id: string;
          artist_share: number;
          partner_share: number;
          studio_share?: number;
          status?: 'PENDING_VERIFICATION' | 'ACTIVE' | 'SUSPENDED' | 'TERMINATED';
          verification_photo?: string | null;
          verification_location?: Json | null;
          verified_at?: string | null;
          total_sales?: number;
          total_earnings?: number;
          partner_notified?: boolean;
          created_at?: string;
          activated_at?: string | null;
        };
        Update: {
          id?: string;
          code_id?: string;
          partner_id?: string;
          artist_share?: number;
          partner_share?: number;
          studio_share?: number;
          status?: 'PENDING_VERIFICATION' | 'ACTIVE' | 'SUSPENDED' | 'TERMINATED';
          verification_photo?: string | null;
          verification_location?: Json | null;
          verified_at?: string | null;
          total_sales?: number;
          total_earnings?: number;
          partner_notified?: boolean;
          created_at?: string;
          activated_at?: string | null;
        };
      };
      orders: {
        Row: {
          id: string;
          customer_id: string;
          customer_email: string | null;
          customer_name: string | null;
          status: 'PENDING_PAYMENT' | 'PAYMENT_RECEIVED' | 'IN_PRODUCTION' | 'SHIPPED' | 'DELIVERED' | 'CANCELLED' | 'REFUNDED' | 'DISPUTED';
          subtotal: number;
          tax_amount: number;
          shipping_amount: number;
          discount_amount: number;
          total: number;
          currency: string;
          stripe_payment_intent_id: string | null;
          stripe_charge_id: string | null;
          shipping_address: Json | null;
          shipping_method: string | null;
          tracking_number: string | null;
          shipped_at: string | null;
          delivered_at: string | null;
          created_at: string;
          updated_at: string;
          paid_at: string | null;
        };
        Insert: {
          id?: string;
          customer_id: string;
          customer_email?: string | null;
          customer_name?: string | null;
          status?: 'PENDING_PAYMENT' | 'PAYMENT_RECEIVED' | 'IN_PRODUCTION' | 'SHIPPED' | 'DELIVERED' | 'CANCELLED' | 'REFUNDED' | 'DISPUTED';
          subtotal: number;
          tax_amount?: number;
          shipping_amount?: number;
          discount_amount?: number;
          total: number;
          currency?: string;
          stripe_payment_intent_id?: string | null;
          stripe_charge_id?: string | null;
          shipping_address?: Json | null;
          shipping_method?: string | null;
          tracking_number?: string | null;
          shipped_at?: string | null;
          delivered_at?: string | null;
          created_at?: string;
          updated_at?: string;
          paid_at?: string | null;
        };
        Update: {
          id?: string;
          customer_id?: string;
          customer_email?: string | null;
          customer_name?: string | null;
          status?: 'PENDING_PAYMENT' | 'PAYMENT_RECEIVED' | 'IN_PRODUCTION' | 'SHIPPED' | 'DELIVERED' | 'CANCELLED' | 'REFUNDED' | 'DISPUTED';
          subtotal?: number;
          tax_amount?: number;
          shipping_amount?: number;
          discount_amount?: number;
          total?: number;
          currency?: string;
          stripe_payment_intent_id?: string | null;
          stripe_charge_id?: string | null;
          shipping_address?: Json | null;
          shipping_method?: string | null;
          tracking_number?: string | null;
          shipped_at?: string | null;
          delivered_at?: string | null;
          created_at?: string;
          updated_at?: string;
          paid_at?: string | null;
        };
      };
      order_items: {
        Row: {
          id: string;
          order_id: string;
          product_id: string;
          product_name: string;
          design_title: string;
          artist_name: string;
          artist_id: string;
          mockup_image: string;
          size: string;
          color: string;
          unit_price: number;
          quantity: number;
          total: number;
          has_partnership: boolean;
          production_status: string;
          print_file_url: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          order_id: string;
          product_id: string;
          product_name: string;
          design_title: string;
          artist_name: string;
          artist_id: string;
          mockup_image: string;
          size: string;
          color: string;
          unit_price: number;
          quantity: number;
          total: number;
          has_partnership?: boolean;
          production_status?: string;
          print_file_url?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          order_id?: string;
          product_id?: string;
          product_name?: string;
          design_title?: string;
          artist_name?: string;
          artist_id?: string;
          mockup_image?: string;
          size?: string;
          color?: string;
          unit_price?: number;
          quantity?: number;
          total?: number;
          has_partnership?: boolean;
          production_status?: string;
          print_file_url?: string | null;
          created_at?: string;
        };
      };
      payouts: {
        Row: {
          id: string;
          user_id: string;
          period_start: string;
          period_end: string;
          gross_amount: number;
          platform_fees: number;
          tax_withheld: number;
          net_amount: number;
          status: 'PENDING' | 'PROCESSING' | 'COMPLETED' | 'FAILED' | 'HELD_FOR_REVIEW';
          stripe_transfer_id: string | null;
          processed_at: string | null;
          completed_at: string | null;
          failed_at: string | null;
          failure_reason: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          period_start: string;
          period_end: string;
          gross_amount: number;
          platform_fees: number;
          tax_withheld?: number;
          net_amount: number;
          status?: 'PENDING' | 'PROCESSING' | 'COMPLETED' | 'FAILED' | 'HELD_FOR_REVIEW';
          stripe_transfer_id?: string | null;
          processed_at?: string | null;
          completed_at?: string | null;
          failed_at?: string | null;
          failure_reason?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          period_start?: string;
          period_end?: string;
          gross_amount?: number;
          platform_fees?: number;
          tax_withheld?: number;
          net_amount?: number;
          status?: 'PENDING' | 'PROCESSING' | 'COMPLETED' | 'FAILED' | 'HELD_FOR_REVIEW';
          stripe_transfer_id?: string | null;
          processed_at?: string | null;
          completed_at?: string | null;
          failed_at?: string | null;
          failure_reason?: string | null;
          created_at?: string;
        };
      };
      reviews: {
        Row: {
          id: string;
          customer_id: string;
          product_id: string;
          rating: number;
          title: string | null;
          content: string;
          images: string[];
          is_verified_purchase: boolean;
          is_public: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          customer_id: string;
          product_id: string;
          rating: number;
          title?: string | null;
          content: string;
          images?: string[];
          is_verified_purchase?: boolean;
          is_public?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          customer_id?: string;
          product_id?: string;
          rating?: number;
          title?: string | null;
          content?: string;
          images?: string[];
          is_verified_purchase?: boolean;
          is_public?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
};
