-- ============================================
-- MIGRATION: 000002_unified_schema
-- Unifies the database schema for production
-- ============================================

-- 1. Fix order_items to support product_designs
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS product_design_id UUID REFERENCES product_designs(id);
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS total_price INTEGER;
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS fulfillment_partner_id UUID REFERENCES fulfillment_partners(id);
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS fulfillment_status TEXT DEFAULT 'unassigned' CHECK (fulfillment_status IN ('unassigned', 'assigned', 'in_production', 'ready_to_ship', 'shipped', 'delivered'));
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS fulfillment_notes TEXT;

-- ============================================
-- STIGMATOR: ENHANCED PARTNERSHIP SYSTEM
-- Multi-Design Garment Support
-- ============================================

-- Partnership Codes (Generated by artist for tattoo clients)
-- This is SEPARATE from garment uploads - it's the pre-arrangement
CREATE TABLE partnership_codes (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    code TEXT UNIQUE NOT NULL, -- e.g., "INK-ALEX-2024-X7K9"
    design_id UUID REFERENCES designs(id) ON DELETE CASCADE NOT NULL,
    artist_id UUID REFERENCES profiles(id) NOT NULL,
    studio_id UUID REFERENCES studios(id), -- Optional: linked studio
    
    -- Split configuration (percentages as integers, total must = 100)
    -- These splits are from the ARTIST'S SHARE only
    -- Platform takes 15% at garment level, these splits happen from remaining 85%
    artist_share INTEGER NOT NULL DEFAULT 50, -- Artist keeps this % of their earnings
    client_share INTEGER NOT NULL DEFAULT 20, -- Client (tattoo wearer) gets this %
    studio_share INTEGER NOT NULL DEFAULT 0,  -- Studio gets this % (optional)
    
    -- Validation: artist_share + client_share + studio_share = 100
    
    -- Status
    status TEXT NOT NULL CHECK (status IN ('active', 'redeemed', 'expired', 'revoked')) DEFAULT 'active',
    max_uses INTEGER DEFAULT 1, -- Usually 1:1 partnership, but can be multiple for flash
    uses_remaining INTEGER DEFAULT 1,
    
    -- Client info (filled when code is created, confirmed when redeemed)
    intended_client_name TEXT,
    intended_client_email TEXT,
    tattoo_location TEXT, -- e.g., "LEFT FOREARM", "FULL BACK"
    session_date DATE,
    notes TEXT,
    
    -- Timestamps
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    redeemed_at TIMESTAMPTZ,
    redeemed_by UUID REFERENCES profiles(id),
    
    -- Validation constraint
    CONSTRAINT valid_partnership_splits CHECK (artist_share + client_share + studio_share = 100),
    CONSTRAINT positive_partnership_splits CHECK (artist_share >= 0 AND client_share >= 0 AND studio_share >= 0)
);

-- User Design Partnerships (When someone redeems a code)
CREATE TABLE design_partnerships (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    partnership_code_id UUID REFERENCES partnership_codes(id) NOT NULL,
    design_id UUID REFERENCES designs(id) NOT NULL,
    artist_id UUID REFERENCES profiles(id) NOT NULL,
    partner_id UUID REFERENCES profiles(id) NOT NULL, -- The tattoo wearer (client)
    studio_id UUID REFERENCES studios(id), -- If studio is involved
    
    -- Their agreed split (copied from code at redemption)
    artist_share INTEGER NOT NULL,
    client_share INTEGER NOT NULL,
    studio_share INTEGER NOT NULL,
    
    -- Verification
    verification_status TEXT NOT NULL CHECK (verification_status IN ('pending', 'verified', 'rejected')) DEFAULT 'pending',
    verification_photo_url TEXT, -- Photo of the actual tattoo
    verified_at TIMESTAMPTZ,
    verified_by UUID REFERENCES profiles(id),
    
    -- Earnings tracking (from this specific partnership)
    total_earnings INTEGER DEFAULT 0, -- In cents
    lifetime_sales INTEGER DEFAULT 0,
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(design_id, partner_id) -- One partnership per design per person
);

-- GARMENT-LEVEL PARTNERSHIPS
-- This is where the magic happens for multi-design garments

-- A garment can have multiple designs from different artists
-- Each design can have multiple partners
-- All splits must be tracked

CREATE TABLE garment_design_partnerships (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    
    -- Links
    product_design_id UUID REFERENCES product_designs(id) NOT NULL, -- The garment with design applied
    design_partnership_id UUID REFERENCES design_partnerships(id) NOT NULL, -- The specific partner
    
    -- The split percentages (copied at time of garment creation to prevent changes)
    artist_share INTEGER NOT NULL,
    client_share INTEGER NOT NULL,
    studio_share INTEGER NOT NULL,
    
    -- Calculated earnings for this specific garment
    total_garment_earnings INTEGER DEFAULT 0,
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(product_design_id, design_partnership_id)
);

-- EARNINGS BREAKDOWN
-- Every sale must track exactly who gets what

-- Payouts (artist/partner withdrawal requests)
CREATE TABLE payouts (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    recipient_id UUID REFERENCES profiles(id) NOT NULL,
    amount INTEGER NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('pending', 'processing', 'paid', 'failed')) DEFAULT 'pending',
    stripe_account_id TEXT,
    stripe_transfer_id TEXT,
    processed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_payouts_recipient ON payouts(recipient_id);
CREATE INDEX idx_payouts_status ON payouts(status);

CREATE TABLE earnings_breakdown (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    order_item_id UUID REFERENCES order_items(id) NOT NULL,
    
    -- Sale info
    sale_amount INTEGER NOT NULL, -- Total sale price in cents
    platform_fee INTEGER NOT NULL, -- 15% of sale
    remaining_amount INTEGER NOT NULL, -- 70% to distribute
    
    -- For single-design garments, simple split
    -- For multi-design garments, each design gets proportional share
    
    -- Who gets paid
    recipient_id UUID REFERENCES profiles(id) NOT NULL,
    recipient_type TEXT NOT NULL CHECK (recipient_type IN ('artist', 'client', 'studio', 'platform')),
    
    -- Their share of this specific sale
    amount INTEGER NOT NULL,
    percentage DECIMAL(5,2) NOT NULL, -- What % of remaining_amount they got
    
    -- Which design this earning is for (if multi-design)
    design_id UUID REFERENCES designs(id),
    
    -- Status
    paid BOOLEAN DEFAULT FALSE,
    paid_at TIMESTAMPTZ,
    payout_id UUID REFERENCES payouts(id),
    
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- MULTI-DESIGN GARMENT TRACKING
-- When a garment has designs from multiple artists

CREATE TABLE garment_designs (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    product_design_id UUID REFERENCES product_designs(id) NOT NULL, -- The garment
    design_id UUID REFERENCES designs(id) NOT NULL, -- Individual design
    artist_id UUID REFERENCES profiles(id) NOT NULL,
    
    -- Placement info
    placement_area TEXT, -- e.g., "left_sleeve", "back_panel"
    placement_order INTEGER DEFAULT 0, -- Layering order
    
    -- Revenue share for this design on this garment
    -- If 3 designs on garment, each might get 33.33% of the 70%
    revenue_percentage DECIMAL(5,2) NOT NULL DEFAULT 100.00,
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(product_design_id, design_id)
);

-- INDICES for performance
CREATE INDEX idx_partnership_codes_code ON partnership_codes(code);
CREATE INDEX idx_partnership_codes_design ON partnership_codes(design_id);
CREATE INDEX idx_partnership_codes_status ON partnership_codes(status);
CREATE INDEX idx_design_partnerships_partner ON design_partnerships(partner_id);
CREATE INDEX idx_design_partnerships_design ON design_partnerships(design_id);
CREATE INDEX idx_garment_designs_product ON garment_designs(product_design_id);
CREATE INDEX idx_earnings_recipient ON earnings_breakdown(recipient_id);
CREATE INDEX idx_earnings_order ON earnings_breakdown(order_item_id);

-- FUNCTIONS

-- Auto-generate unique code
CREATE OR REPLACE FUNCTION generate_partnership_code()
RETURNS TRIGGER AS $$
DECLARE
    artist_initials TEXT;
    year TEXT;
    random_part TEXT;
BEGIN
    -- Get artist initials from profile
    SELECT COALESCE(SUBSTRING(UPPER(display_name), 1, 2), 'XX')
    INTO artist_initials
    FROM profiles
    WHERE id = NEW.artist_id;
    
    year := EXTRACT(YEAR FROM NOW())::TEXT;
    random_part := UPPER(SUBSTRING(MD5(NEW.id::TEXT), 1, 4));
    
    NEW.code := 'INK-' || artist_initials || year || '-' || random_part;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_partnership_code BEFORE INSERT ON partnership_codes
    FOR EACH ROW EXECUTE FUNCTION generate_partnership_code();

-- Calculate earnings for a sale with multiple partners
CREATE OR REPLACE FUNCTION calculate_garment_earnings(
    p_product_design_id UUID,
    p_sale_amount INTEGER
)
RETURNS TABLE (
    recipient_id UUID,
    recipient_type TEXT,
    amount INTEGER,
    percentage DECIMAL
) AS $$
DECLARE
    v_platform_fee INTEGER;
    v_remaining INTEGER;
    v_garment_design RECORD;
    v_partnership RECORD;
    v_design_share INTEGER;
BEGIN
    -- Platform takes 15%
    v_platform_fee := (p_sale_amount * 0.15)::INTEGER;
    v_remaining := p_sale_amount - v_platform_fee;
    
    -- Return platform fee
    RETURN QUERY SELECT 
        NULL::UUID,
        'platform'::TEXT,
        v_platform_fee,
        30.00::DECIMAL;
    
    -- Get all designs on this garment
    FOR v_garment_design IN 
        SELECT gd.*, d.artist_id
        FROM garment_designs gd
        JOIN designs d ON d.id = gd.design_id
        WHERE gd.product_design_id = p_product_design_id
    LOOP
        -- This design's share of the remaining 70%
        v_design_share := (v_remaining * (v_garment_design.revenue_percentage / 100))::INTEGER;
        
        -- Check if design has partnerships
        FOR v_partnership IN 
            SELECT dp.*, dp.artist_id as artist_user_id
            FROM garment_design_partnerships gdp
            JOIN design_partnerships dp ON dp.id = gdp.design_partnership_id
            WHERE gdp.product_design_id = p_product_design_id
            AND dp.design_id = v_garment_design.design_id
        LOOP
            -- Artist gets their share
            RETURN QUERY SELECT 
                v_partnership.artist_user_id,
                'artist'::TEXT,
                (v_design_share * (v_partnership.artist_share / 100))::INTEGER,
                (v_garment_design.revenue_percentage * (v_partnership.artist_share / 100))::DECIMAL;
            
            -- Client gets their share
            IF v_partnership.client_share > 0 THEN
                RETURN QUERY SELECT 
                    v_partnership.partner_id,
                    'client'::TEXT,
                    (v_design_share * (v_partnership.client_share / 100))::INTEGER,
                    (v_garment_design.revenue_percentage * (v_partnership.client_share / 100))::DECIMAL;
            END IF;
            
            -- Studio gets their share
            IF v_partnership.studio_share > 0 AND v_partnership.studio_id IS NOT NULL THEN
                RETURN QUERY SELECT 
                    v_partnership.studio_id,
                    'studio'::TEXT,
                    (v_design_share * (v_partnership.studio_share / 100))::INTEGER,
                    (v_garment_design.revenue_percentage * (v_partnership.studio_share / 100))::DECIMAL;
            END IF;
        END LOOP;
        
        -- If no partnerships, artist gets 100% of design share
        IF NOT EXISTS (
            SELECT 1 FROM garment_design_partnerships 
            WHERE product_design_id = p_product_design_id
            AND design_partnership_id IN (
                SELECT id FROM design_partnerships WHERE design_id = v_garment_design.design_id
            )
        ) THEN
            RETURN QUERY SELECT 
                v_garment_design.artist_id,
                'artist'::TEXT,
                v_design_share,
                v_garment_design.revenue_percentage::DECIMAL;
        END IF;
    END LOOP;
    
    RETURN;
END;
$$ LANGUAGE plpgsql;

-- RLS POLICIES
ALTER TABLE partnership_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE design_partnerships ENABLE ROW LEVEL SECURITY;
ALTER TABLE garment_design_partnerships ENABLE ROW LEVEL SECURITY;
ALTER TABLE garment_designs ENABLE ROW LEVEL SECURITY;
ALTER TABLE earnings_breakdown ENABLE ROW LEVEL SECURITY;

-- Artists can manage their own codes
CREATE POLICY "Artists manage their codes" ON partnership_codes
    FOR ALL USING (auth.uid() = artist_id);

-- Partners can view their partnerships
CREATE POLICY "Partners view their data" ON design_partnerships
    FOR SELECT USING (auth.uid() = partner_id OR auth.uid() = artist_id);

-- Earnings visible to recipients
CREATE POLICY "Recipients view earnings" ON earnings_breakdown
    FOR SELECT USING (auth.uid() = recipient_id);

-- RLS for payouts
ALTER TABLE payouts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Recipients view payouts" ON payouts
    FOR SELECT USING (auth.uid() = recipient_id);

CREATE POLICY "Admins manage payouts" ON payouts
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM profiles
            WHERE id = auth.uid() AND role IN ('ADMIN', 'SUPER_ADMIN')
        )
    );
-- ============================================
-- STIGMATOR: DEPOSIT RECOUP SYSTEM
-- Kickstarter-style artist investment recovery
-- ============================================

-- Add deposit tracking to product_designs
ALTER TABLE product_designs ADD COLUMN IF NOT EXISTS deposit_amount INTEGER DEFAULT 0; -- In cents
ALTER TABLE product_designs ADD COLUMN IF NOT EXISTS deposit_recoup_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE product_designs ADD COLUMN IF NOT EXISTS deposit_recoup_sales_target INTEGER DEFAULT 0; -- How many sales to recoup
ALTER TABLE product_designs ADD COLUMN IF NOT EXISTS deposit_recouped_sales_count INTEGER DEFAULT 0; -- Track progress
ALTER TABLE product_designs ADD COLUMN IF NOT EXISTS deposit_recouped_at TIMESTAMPTZ; -- When fully recouped

-- Track recoup payments per order
CREATE TABLE deposit_recoup_payments (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    product_design_id UUID REFERENCES product_designs(id) NOT NULL,
    order_item_id UUID REFERENCES order_items(id) NOT NULL,
    
    -- How much went to recoup
    amount INTEGER NOT NULL, -- In cents
    
    -- Running totals
    cumulative_recouped INTEGER NOT NULL, -- Total recouped so far
    remaining_to_recoup INTEGER NOT NULL, -- What's left
    
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Function to calculate earnings with deposit recoup
CREATE OR REPLACE FUNCTION calculate_earnings_with_recoup(
    p_order_item_id UUID,
    p_sale_amount INTEGER
)
RETURNS TABLE (
    recipient_id UUID,
    recipient_type TEXT,
    amount INTEGER,
    earnings_type TEXT, -- 'deposit_recoup', 'normal_share', 'platform_fee'
    description TEXT
) AS $$
DECLARE
    v_product_design RECORD;
    v_remaining_after_platform INTEGER;
    v_recoup_amount INTEGER;
    v_normal_share_amount INTEGER;
    v_partnership RECORD;
    v_garment_design RECORD;
    v_total_parts INTEGER;
    v_design_remaining INTEGER;
BEGIN
    -- Get product design info
    SELECT * INTO v_product_design
    FROM product_designs
    WHERE id = (SELECT product_design_id FROM order_items WHERE id = p_order_item_id);
    
    -- Platform takes 15% first
    RETURN QUERY SELECT 
        NULL::UUID, 
        'platform'::TEXT, 
        (p_sale_amount * 0.15)::INTEGER,
        'platform_fee'::TEXT,
        'Stigmator platform fee (15%)'::TEXT;
    
    v_remaining_after_platform := (p_sale_amount * 0.70)::INTEGER;
    
    -- Check if deposit recoup is active
    IF v_product_design.deposit_recoup_enabled 
       AND v_product_design.deposit_recouped_sales_count < v_product_design.deposit_recoup_sales_target THEN
        
        -- Calculate how much can go to recoup this sale
        -- Give artist UP TO 100% of remaining until deposit recouped
        v_recoup_amount := LEAST(
            v_remaining_after_platform,
            v_product_design.deposit_amount - (
                SELECT COALESCE(SUM(amount), 0) 
                FROM deposit_recoup_payments 
                WHERE product_design_id = v_product_design.id
            )
        );
        
        IF v_recoup_amount > 0 THEN
            -- Pay artist the recoup amount
            RETURN QUERY SELECT 
                v_product_design.artist_id,
                'artist'::TEXT,
                v_recoup_amount,
                'deposit_recoup'::TEXT,
                'Deposit recoup payment'::TEXT;
            
            -- Record the recoup payment
            INSERT INTO deposit_recoup_payments (
                product_design_id,
                order_item_id,
                amount,
                cumulative_recouped,
                remaining_to_recoup
            ) VALUES (
                v_product_design.id,
                p_order_item_id,
                v_recoup_amount,
                (
                    SELECT COALESCE(SUM(amount), 0) + v_recoup_amount
                    FROM deposit_recoup_payments
                    WHERE product_design_id = v_product_design.id
                ),
                v_product_design.deposit_amount - (
                    SELECT COALESCE(SUM(amount), 0) + v_recoup_amount
                    FROM deposit_recoup_payments
                    WHERE product_design_id = v_product_design.id
                )
            );
            
            -- Update running count
            UPDATE product_designs 
            SET deposit_recouped_sales_count = deposit_recouped_sales_count + 1,
                deposit_recouped_at = CASE 
                    WHEN deposit_recouped_sales_count + 1 >= deposit_recoup_sales_target THEN NOW()
                    ELSE NULL
                END
            WHERE id = v_product_design.id;
            
            v_remaining_after_platform := v_remaining_after_platform - v_recoup_amount;
        END IF;
    END IF;
    
    -- If there's remaining amount, distribute to partnerships (normal split)
    IF v_remaining_after_platform > 0 THEN
        -- Check if this garment has multiple designs
        SELECT COUNT(*) INTO v_total_parts
        FROM garment_designs
        WHERE product_design_id = v_product_design.id;
        
        IF v_total_parts > 1 THEN
            -- Multi-design garment - split proportionally
            FOR v_garment_design IN 
                SELECT gd.*, dp.artist_id as design_artist_id
                FROM garment_designs gd
                JOIN designs d ON d.id = gd.design_id
                JOIN product_designs dp ON dp.design_id = d.id
                WHERE gd.product_design_id = v_product_design.id
            LOOP
                v_design_remaining := (v_remaining_after_platform * (v_garment_design.revenue_percentage / 100))::INTEGER;
                
                -- Get partnerships for this design
                FOR v_partnership IN 
                    SELECT dp.*, dp.artist_id as artist_user_id
                    FROM garment_design_partnerships gdp
                    JOIN design_partnerships dp ON dp.id = gdp.design_partnership_id
                    WHERE gdp.product_design_id = v_product_design.id
                    AND dp.design_id = v_garment_design.design_id
                LOOP
                    -- Artist gets their share
                    IF v_partnership.artist_share > 0 THEN
                        RETURN QUERY SELECT 
                            v_partnership.artist_user_id,
                            'artist'::TEXT,
                            (v_design_remaining * (v_partnership.artist_share / 100))::INTEGER,
                            'normal_share'::TEXT,
                            'Artist share of design revenue'::TEXT;
                    END IF;
                    
                    -- Client gets their share
                    IF v_partnership.client_share > 0 THEN
                        RETURN QUERY SELECT 
                            v_partnership.partner_id,
                            'client'::TEXT,
                            (v_design_remaining * (v_partnership.client_share / 100))::INTEGER,
                            'normal_share'::TEXT,
                            'Client partnership share'::TEXT;
                    END IF;
                    
                    -- Studio gets their share
                    IF v_partnership.studio_share > 0 AND v_partnership.studio_id IS NOT NULL THEN
                        RETURN QUERY SELECT 
                            v_partnership.studio_id,
                            'studio'::TEXT,
                            (v_design_remaining * (v_partnership.studio_share / 100))::INTEGER,
                            'normal_share'::TEXT,
                            'Studio partnership share'::TEXT;
                    END IF;
                END LOOP;
                
                -- No partnerships? Artist gets all
                IF NOT EXISTS (
                    SELECT 1 FROM garment_design_partnerships 
                    WHERE product_design_id = v_product_design.id
                    AND design_partnership_id IN (
                        SELECT id FROM design_partnerships WHERE design_id = v_garment_design.design_id
                    )
                ) THEN
                    RETURN QUERY SELECT 
                        v_garment_design.design_artist_id,
                        'artist'::TEXT,
                        v_design_remaining,
                        'normal_share'::TEXT,
                        'Artist full share (no partners)'::TEXT;
                END IF;
            END LOOP;
        ELSE
            -- Single design - check for partnerships
            FOR v_partnership IN 
                SELECT dp.*, dp.artist_id as artist_user_id
                FROM garment_design_partnerships gdp
                JOIN design_partnerships dp ON dp.id = gdp.design_partnership_id
                WHERE gdp.product_design_id = v_product_design.id
            LOOP
                -- Artist share
                IF v_partnership.artist_share > 0 THEN
                    RETURN QUERY SELECT 
                        v_partnership.artist_user_id,
                        'artist'::TEXT,
                        (v_remaining_after_platform * (v_partnership.artist_share / 100))::INTEGER,
                        'normal_share'::TEXT,
                        'Artist share'::TEXT;
                END IF;
                
                -- Client share
                IF v_partnership.client_share > 0 THEN
                    RETURN QUERY SELECT 
                        v_partnership.partner_id,
                        'client'::TEXT,
                        (v_remaining_after_platform * (v_partnership.client_share / 100))::INTEGER,
                        'normal_share'::TEXT,
                        'Client share'::TEXT;
                END IF;
                
                -- Studio share
                IF v_partnership.studio_share > 0 AND v_partnership.studio_id IS NOT NULL THEN
                    RETURN QUERY SELECT 
                        v_partnership.studio_id,
                        'studio'::TEXT,
                        (v_remaining_after_platform * (v_partnership.studio_share / 100))::INTEGER,
                        'normal_share'::TEXT,
                        'Studio share'::TEXT;
                END IF;
            END LOOP;
            
            -- No partnerships? Artist keeps all
            IF NOT EXISTS (
                SELECT 1 FROM garment_design_partnerships 
                WHERE product_design_id = v_product_design.id
            ) THEN
                RETURN QUERY SELECT 
                    v_product_design.artist_id,
                    'artist'::TEXT,
                    v_remaining_after_platform,
                    'normal_share'::TEXT,
                    'Artist full earnings (no partners)'::TEXT;
            END IF;
        END IF;
    END IF;
    
    RETURN;
END;
$$ LANGUAGE plpgsql;

-- View for artist dashboard showing recoup progress
CREATE VIEW artist_recoup_status AS
SELECT 
    pd.id as product_design_id,
    pd.design_id,
    d.title as design_title,
    pd.artist_id,
    pd.deposit_amount,
    pd.deposit_recoup_enabled,
    pd.deposit_recoup_sales_target,
    pd.deposit_recouped_sales_count,
    pd.deposit_recouped_at,
    CASE 
        WHEN pd.deposit_recoup_enabled THEN
            ROUND((pd.deposit_recouped_sales_count::NUMERIC / pd.deposit_recoup_sales_target) * 100, 1)
        ELSE NULL
    END as recoup_percentage,
    COALESCE(
        (SELECT SUM(amount) FROM deposit_recoup_payments WHERE product_design_id = pd.id),
        0
    ) as total_recouped_amount,
    pd.deposit_amount - COALESCE(
        (SELECT SUM(amount) FROM deposit_recoup_payments WHERE product_design_id = pd.id),
        0
    ) as remaining_to_recoup
FROM product_designs pd
JOIN designs d ON d.id = pd.design_id
WHERE pd.deposit_recoup_enabled = TRUE;

-- Indexes
CREATE INDEX idx_deposit_recoup_payments_design ON deposit_recoup_payments(product_design_id);
CREATE INDEX idx_product_designs_recoup ON product_designs(deposit_recoup_enabled, deposit_recouped_sales_count);
-- ============================================
-- REFERRAL SYSTEM
-- 5% commission to referrer for first 6 months
-- ============================================

-- Referral tracking table
CREATE TABLE referrals (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    referrer_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
    referred_artist_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
    referral_code TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('pending', 'completed', 'expired')) DEFAULT 'pending',
    
    -- Commission tracking
    commission_rate DECIMAL(5,4) NOT NULL DEFAULT 0.05, -- 5%
    commission_duration_months INTEGER NOT NULL DEFAULT 6,
    
    -- Tracking
    total_sales_generated INTEGER DEFAULT 0, -- in cents
    total_commission_paid INTEGER DEFAULT 0, -- in cents
    
    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT NOW(),
    artist_approved_at TIMESTAMPTZ, -- When artist was approved
    expires_at TIMESTAMPTZ, -- 6 months after approval
    
    UNIQUE(referred_artist_id), -- One referrer per artist
    UNIQUE(referral_code)
);

-- Referral earnings (line items for each sale)
CREATE TABLE referral_earnings (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    referral_id UUID REFERENCES referrals(id) ON DELETE CASCADE NOT NULL,
    order_item_id UUID REFERENCES order_items(id) ON DELETE CASCADE NOT NULL,
    
    -- Earnings breakdown
    sale_amount INTEGER NOT NULL, -- in cents
    commission_amount INTEGER NOT NULL, -- in cents (5% of sale)
    
    -- Status
    status TEXT NOT NULL CHECK (status IN ('pending', 'paid', 'cancelled')) DEFAULT 'pending',
    paid_at TIMESTAMPTZ,
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    
    UNIQUE(order_item_id) -- One referral earning per order item
);

-- Indexes
CREATE INDEX idx_referrals_referrer ON referrals(referrer_id);
CREATE INDEX idx_referrals_artist ON referrals(referred_artist_id);
CREATE INDEX idx_referrals_status ON referrals(status);
CREATE INDEX idx_referrals_expires ON referrals(expires_at);
CREATE INDEX idx_referral_earnings_referral ON referral_earnings(referral_id);
CREATE INDEX idx_referral_earnings_status ON referral_earnings(status);

-- RLS Policies
ALTER TABLE referrals ENABLE ROW LEVEL SECURITY;
ALTER TABLE referral_earnings ENABLE ROW LEVEL SECURITY;

-- Referrers can view their own referrals
CREATE POLICY "Referrers can view their referrals"
ON referrals FOR SELECT
USING (auth.uid() = referrer_id);

-- Artists can see who referred them
CREATE POLICY "Artists can see their referrer"
ON referrals FOR SELECT
USING (auth.uid() = referred_artist_id);

-- System can create referrals
CREATE POLICY "System can create referrals"
ON referrals FOR INSERT
WITH CHECK (true);

-- System can update referrals
CREATE POLICY "System can update referrals"
ON referrals FOR UPDATE
USING (true);

-- Referral earnings policies
CREATE POLICY "Referrers can view their earnings"
ON referral_earnings FOR SELECT
USING (
    EXISTS (
        SELECT 1 FROM referrals 
        WHERE referrals.id = referral_earnings.referral_id 
        AND referrals.referrer_id = auth.uid()
    )
);

-- ============================================
-- FUNCTIONS FOR REFERRAL SYSTEM
-- ============================================

-- Function to create a referral when artist applies
CREATE OR REPLACE FUNCTION create_referral_on_artist_apply()
RETURNS TRIGGER AS $$
BEGIN
    -- Check if a referral code was provided
    IF NEW.referral_code IS NOT NULL THEN
        -- Find the referrer
        INSERT INTO referrals (
            referrer_id,
            referred_artist_id,
            referral_code,
            status,
            artist_approved_at,
            expires_at
        )
        SELECT 
            r.referrer_id,
            NEW.id,
            NEW.referral_code,
            'completed',
            NOW(),
            NOW() + INTERVAL '6 months'
        FROM referrals r
        WHERE r.referral_code = NEW.referral_code
        AND r.status = 'pending'
        ON CONFLICT DO NOTHING;
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Function to calculate referral commission on sale
CREATE OR REPLACE FUNCTION calculate_referral_commission(
    p_order_item_id UUID,
    p_sale_amount INTEGER
) RETURNS INTEGER AS $$
DECLARE
    v_referral_id UUID;
    v_commission_rate DECIMAL(5,4);
    v_expires_at TIMESTAMPTZ;
    v_commission_amount INTEGER;
BEGIN
    -- Find active referral for this artist
    SELECT 
        r.id,
        r.commission_rate,
        r.expires_at
    INTO 
        v_referral_id,
        v_commission_rate,
        v_expires_at
    FROM referrals r
    JOIN order_items oi ON oi.id = p_order_item_id
    JOIN product_designs pd ON pd.id = oi.product_design_id
    WHERE r.referred_artist_id = pd.artist_id
    AND r.status = 'completed'
    AND r.expires_at > NOW();
    
    -- If no active referral, return 0
    IF v_referral_id IS NULL THEN
        RETURN 0;
    END IF;
    
    -- Calculate commission (5% of sale)
    v_commission_amount := (p_sale_amount * v_commission_rate)::INTEGER;
    
    -- Insert referral earning record
    INSERT INTO referral_earnings (
        referral_id,
        order_item_id,
        sale_amount,
        commission_amount
    ) VALUES (
        v_referral_id,
        p_order_item_id,
        p_sale_amount,
        v_commission_amount
    )
    ON CONFLICT (order_item_id) DO UPDATE
    SET commission_amount = EXCLUDED.commission_amount;
    
    -- Update referral totals
    UPDATE referrals
    SET 
        total_sales_generated = total_sales_generated + p_sale_amount,
        total_commission_paid = total_commission_paid + v_commission_amount
    WHERE id = v_referral_id;
    
    RETURN v_commission_amount;
END;
$$ LANGUAGE plpgsql;

-- Add referral_code to profiles for tracking
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS referral_code TEXT UNIQUE;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS referred_by UUID REFERENCES profiles(id);

-- Function to generate unique referral code for each user
CREATE OR REPLACE FUNCTION generate_referral_code()
RETURNS TRIGGER AS $$
BEGIN
    NEW.referral_code := UPPER(SUBSTRING(MD5(NEW.id::TEXT), 1, 8));
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_referral_code
    BEFORE INSERT ON profiles
    FOR EACH ROW
    EXECUTE FUNCTION generate_referral_code();
-- ============================================
-- STIGMATOR: MANUFACTURING WORKFLOW
-- Complete garment production system
-- ============================================

-- Garment Production Status
ALTER TABLE product_designs ADD COLUMN IF NOT EXISTS production_status TEXT DEFAULT 'draft' 
  CHECK (production_status IN ('draft', 'deposit_paid', 'pending_manufacturer', 'manufacturer_review', 'approved', 'in_production', 'sample_created', 'live', 'paused', 'sold_out', 'archived'));

-- Manufacturer Assignment
ALTER TABLE product_designs ADD COLUMN IF NOT EXISTS manufacturer_id UUID REFERENCES fulfillment_partners(id);
ALTER TABLE product_designs ADD COLUMN IF NOT EXISTS manufacturer_assigned_at TIMESTAMPTZ;
ALTER TABLE product_designs ADD COLUMN IF NOT EXISTS manufacturer_approved_at TIMESTAMPTZ;
ALTER TABLE product_designs ADD COLUMN IF NOT EXISTS manufacturer_declined_at TIMESTAMPTZ;
ALTER TABLE product_designs ADD COLUMN IF NOT EXISTS manufacturer_decline_reason TEXT;

-- Manufacturing Attempts (track if multiple manufacturers needed)
CREATE TABLE manufacturing_attempts (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    product_design_id UUID REFERENCES product_designs(id) NOT NULL,
    manufacturer_id UUID REFERENCES fulfillment_partners(id) NOT NULL,
    
    status TEXT NOT NULL CHECK (status IN ('pending', 'approved', 'declined', 'withdrawn')),
    decline_reason TEXT,
    
    submitted_at TIMESTAMPTZ DEFAULT NOW(),
    responded_at TIMESTAMPTZ,
    
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Mockup Delivery Options
ALTER TABLE product_designs ADD COLUMN IF NOT EXISTS mockup_delivery_method TEXT DEFAULT 'digital' 
  CHECK (mockup_delivery_method IN ('digital', 'physical'));
ALTER TABLE product_designs ADD COLUMN IF NOT EXISTS mockup_shipping_address JSONB; -- If physical
ALTER TABLE product_designs ADD COLUMN IF NOT EXISTS mockup_shipping_paid BOOLEAN DEFAULT FALSE;
ALTER TABLE product_designs ADD COLUMN IF NOT EXISTS mockup_shipped_at TIMESTAMPTZ;
ALTER TABLE product_designs ADD COLUMN IF NOT EXISTS mockup_tracking_number TEXT;

-- Artist Pricing Control
ALTER TABLE product_designs ADD COLUMN IF NOT EXISTS artist_retail_price INTEGER; -- In cents, artist sets this
ALTER TABLE product_designs ADD COLUMN IF NOT EXISTS suggested_retail_price INTEGER; -- Platform suggestion
ALTER TABLE product_designs ADD COLUMN IF NOT EXISTS manufacturing_cost INTEGER; -- From manufacturer quote
ALTER TABLE product_designs ADD COLUMN IF NOT EXISTS platform_fee_amount INTEGER; -- Calculated (15%)
ALTER TABLE product_designs ADD COLUMN IF NOT EXISTS artist_profit_per_unit INTEGER; -- Calculated

-- Batch/Limited Run Settings
ALTER TABLE product_designs ADD COLUMN IF NOT EXISTS is_limited_run BOOLEAN DEFAULT FALSE;
ALTER TABLE product_designs ADD COLUMN IF NOT EXISTS max_units INTEGER; -- NULL = unlimited
ALTER TABLE product_designs ADD COLUMN IF NOT EXISTS units_sold INTEGER DEFAULT 0;
ALTER TABLE product_designs ADD COLUMN IF NOT EXISTS units_reserved INTEGER DEFAULT 0; -- For bulk artist purchase

-- Bulk Purchase by Artist
ALTER TABLE product_designs ADD COLUMN IF NOT EXISTS artist_bulk_purchase_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE product_designs ADD COLUMN IF NOT EXISTS artist_bulk_quantity INTEGER; -- How many units artist wants
ALTER TABLE product_designs ADD COLUMN IF NOT EXISTS artist_bulk_paid BOOLEAN DEFAULT FALSE;
ALTER TABLE product_designs ADD COLUMN IF NOT EXISTS artist_bulk_shipped BOOLEAN DEFAULT FALSE;
ALTER TABLE product_designs ADD COLUMN IF NOT EXISTS artist_bulk_tracking TEXT;

-- Pre-orders / Campaign Mode
ALTER TABLE product_designs ADD COLUMN IF NOT EXISTS is_campaign_mode BOOLEAN DEFAULT FALSE;
ALTER TABLE product_designs ADD COLUMN IF NOT EXISTS campaign_min_units INTEGER DEFAULT 10; -- Minimum to produce
ALTER TABLE product_designs ADD COLUMN IF NOT EXISTS campaign_ends_at TIMESTAMPTZ;
ALTER TABLE product_designs ADD COLUMN IF NOT EXISTS campaign_success_threshold INTEGER; -- Auto-succeed at X orders

-- Production Queue (for batching)
CREATE TABLE production_queue (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    product_design_id UUID REFERENCES product_designs(id) NOT NULL,
    manufacturer_id UUID REFERENCES fulfillment_partners(id) NOT NULL,
    
    status TEXT NOT NULL CHECK (status IN ('queued', 'in_production', 'quality_check', 'completed', 'shipped')),
    
    quantity INTEGER NOT NULL,
    priority INTEGER DEFAULT 0, -- Higher = sooner
    
    estimated_start TIMESTAMPTZ;
    estimated_completion TIMESTAMPTZ;
    actual_start TIMESTAMPTZ;
    actual_completion TIMESTAMPTZ;
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Manufacturing Quotes (for pricing transparency)
CREATE TABLE manufacturing_quotes (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    product_design_id UUID REFERENCES product_designs(id) NOT NULL,
    manufacturer_id UUID REFERENCES fulfillment_partners(id) NOT NULL,
    
    cost_per_unit INTEGER NOT NULL, -- In cents
    min_order_quantity INTEGER DEFAULT 1,
    setup_fee INTEGER DEFAULT 0,
    shipping_estimate INTEGER, -- To customer
    turnaround_days INTEGER,
    
    is_accepted BOOLEAN DEFAULT FALSE,
    accepted_at TIMESTAMPTZ;
    
    valid_until TIMESTAMPTZ;
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Functions

-- Calculate pricing breakdown
CREATE OR REPLACE FUNCTION calculate_garment_pricing(
    p_manufacturing_cost INTEGER,
    p_desired_retail INTEGER DEFAULT NULL,
    p_platform_fee_percent DECIMAL DEFAULT 15
)
RETURNS TABLE (
    manufacturing_cost INTEGER,
    platform_fee INTEGER,
    remaining INTEGER,
    artist_retail INTEGER,
    artist_profit INTEGER
) AS $$
DECLARE
    v_platform_fee INTEGER;
    v_remaining INTEGER;
    v_retail INTEGER;
BEGIN
    -- If artist sets retail price
    IF p_desired_retail IS NOT NULL THEN
        v_retail := p_desired_retail;
    ELSE
        -- Suggest retail: cost Ã— 3 (standard retail markup)
        v_retail := CEIL(p_manufacturing_cost * 3 / 100) * 100;
    END IF;
    
    v_platform_fee := (v_retail * (p_platform_fee_percent / 100))::INTEGER;
    v_remaining := v_retail - v_platform_fee;
    
    RETURN QUERY SELECT 
        p_manufacturing_cost,
        v_platform_fee,
        v_remaining,
        v_retail,
        v_remaining - p_manufacturing_cost;
END;
$$ LANGUAGE plpgsql;

-- Check if can go live
CREATE OR REPLACE FUNCTION can_garment_go_live(p_product_design_id UUID)
RETURNS BOOLEAN AS $$
DECLARE
    v_status TEXT;
    v_manufacturer_approved BOOLEAN;
    v_sample_approved BOOLEAN;
    v_quote_accepted BOOLEAN;
BEGIN
    SELECT production_status INTO v_status
    FROM product_designs WHERE id = p_product_design_id;
    
    -- Must be approved by manufacturer
    SELECT EXISTS(
        SELECT 1 FROM manufacturing_attempts 
        WHERE product_design_id = p_product_design_id 
        AND status = 'approved'
    ) INTO v_manufacturer_approved;
    
    -- Must have accepted quote
    SELECT EXISTS(
        SELECT 1 FROM manufacturing_quotes 
        WHERE product_design_id = p_product_design_id 
        AND is_accepted = TRUE
    ) INTO v_quote_accepted;
    
    RETURN v_manufacturer_approved AND v_quote_accepted;
END;
$$ LANGUAGE plpgsql;

-- Update production status
CREATE OR REPLACE FUNCTION update_production_status()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := NOW();
    
    -- If manufacturer approved and quote accepted, can go live
    IF NEW.manufacturer_approved_at IS NOT NULL AND 
       EXISTS(SELECT 1 FROM manufacturing_quotes WHERE product_design_id = NEW.id AND is_accepted = TRUE) THEN
        NEW.production_status := 'approved';
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_prod_status BEFORE UPDATE ON product_designs
    FOR EACH ROW EXECUTE FUNCTION update_production_status();

-- Indexes
CREATE INDEX idx_manufacturing_attempts_product ON manufacturing_attempts(product_design_id);
CREATE INDEX idx_manufacturing_quotes_product ON manufacturing_quotes(product_design_id);
CREATE INDEX idx_production_queue_status ON production_queue(status);
CREATE INDEX idx_product_designs_status ON product_designs(production_status);

-- RLS Policies
ALTER TABLE manufacturing_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE manufacturing_quotes ENABLE ROW LEVEL SECURITY;
ALTER TABLE production_queue ENABLE ROW LEVEL SECURITY;

-- Artists can view their manufacturing data
CREATE POLICY "Artists view their manufacturing" ON manufacturing_attempts
    FOR SELECT USING (EXISTS(SELECT 1 FROM product_designs pd WHERE pd.id = product_design_id AND pd.artist_id = auth.uid()));

-- Manufacturers can view their assigned work
CREATE POLICY "Manufacturers view their assignments" ON manufacturing_attempts
    FOR ALL USING (manufacturer_id IN (SELECT id FROM fulfillment_partners WHERE profile_id = auth.uid()));
-- Stigmator 3D Mockup System Schema
-- =================================
-- Database schema for managing mockup presets, rendered images,
-- design assets, and 3D garment models.

-- =============================================
-- 1. MOCKUP PRESETS - Saved mockup configurations
-- =============================================
CREATE TABLE mockup_presets (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    artist_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
    
    -- Identity
    name TEXT NOT NULL,
    description TEXT,
    tags TEXT[],
    
    -- Garment configuration
    garment_type TEXT NOT NULL CHECK (garment_type IN ('tshirt', 'hoodie', 'tank', 'longsleeve', 'sweatpants', 'shorts')),
    variant_id TEXT NOT NULL,
    color_hex TEXT NOT NULL,
    fabric_type TEXT NOT NULL DEFAULT 'cotton',
    
    -- Design configuration
    design_file_id UUID REFERENCES storage.objects(id) ON DELETE SET NULL,
    design_transform JSONB DEFAULT '{"position": {"x": 0, "y": 0}, "scale": 1, "rotation": 0}',
    print_area TEXT DEFAULT 'chest',
    
    -- View configuration
    camera_angle JSONB DEFAULT '{"theta": 0, "phi": 1.57, "radius": 5}',
    lighting_preset TEXT DEFAULT 'studio',
    
    -- Rendered outputs
    thumbnail_url TEXT,
    preview_urls JSONB, -- { "front": "...", "back": "...", "angle": "..." }
    
    -- Metadata
    is_default BOOLEAN DEFAULT false,
    is_public BOOLEAN DEFAULT false,
    usage_count INTEGER DEFAULT 0,
    last_used_at TIMESTAMPTZ,
    
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Indexes for mockup_presets
CREATE INDEX idx_mockup_presets_artist ON mockup_presets(artist_id);
CREATE INDEX idx_mockup_presets_garment ON mockup_presets(garment_type);
CREATE INDEX idx_mockup_presets_public ON mockup_presets(is_public) WHERE is_public = true;
CREATE INDEX idx_mockup_presets_tags ON mockup_presets USING gin(tags);

-- Comments
COMMENT ON TABLE mockup_presets IS 'Saved mockup configurations for artists';
COMMENT ON COLUMN mockup_presets.design_transform IS 'JSON containing position, scale, and rotation of design on garment';
COMMENT ON COLUMN mockup_presets.camera_angle IS 'Spherical coordinates: theta (azimuth), phi (elevation), radius';
COMMENT ON COLUMN mockup_presets.preview_urls IS 'Object with URLs for different rendered angles';

-- =============================================
-- 2. MOCKUP RENDERS - Individual rendered images
-- =============================================
CREATE TABLE mockup_renders (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    preset_id UUID REFERENCES mockup_presets(id) ON DELETE CASCADE NOT NULL,
    
    -- Render specs
    angle TEXT NOT NULL, -- 'front', 'back', 'three-quarter-left', etc.
    width INTEGER NOT NULL,
    height INTEGER NOT NULL,
    format TEXT NOT NULL CHECK (format IN ('png', 'jpg', 'webp')),
    
    -- Storage
    storage_path TEXT NOT NULL, -- path in Supabase Storage
    public_url TEXT NOT NULL,
    file_size_bytes INTEGER,
    
    -- Metadata
    is_primary BOOLEAN DEFAULT false, -- primary image for shop listing
    generation_time_ms INTEGER,
    
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Indexes for mockup_renders
CREATE INDEX idx_mockup_renders_preset ON mockup_renders(preset_id);
CREATE INDEX idx_mockup_renders_primary ON mockup_renders(preset_id, is_primary);
CREATE INDEX idx_mockup_renders_angle ON mockup_renders(angle);

-- Comments
COMMENT ON TABLE mockup_renders IS 'Individual rendered mockup images generated from presets';
COMMENT ON COLUMN mockup_renders.is_primary IS 'Designates the primary render for shop listings';

-- =============================================
-- 3. DESIGN FILES - Uploaded design assets
-- =============================================
CREATE TABLE design_files (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    artist_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
    
    -- File info
    original_name TEXT NOT NULL,
    storage_path TEXT NOT NULL,
    public_url TEXT NOT NULL,
    
    -- Technical specs
    format TEXT NOT NULL CHECK (format IN ('png', 'jpg', 'webp')),
    width INTEGER NOT NULL,
    height INTEGER NOT NULL,
    has_transparency BOOLEAN DEFAULT false,
    file_size_bytes INTEGER NOT NULL,
    
    -- Color analysis
    dominant_colors JSONB, -- [{ "hex": "...", "percent": 0.5 }]
    is_dark_design BOOLEAN, -- auto-detected
    
    -- Usage tracking
    usage_count INTEGER DEFAULT 0,
    last_used_at TIMESTAMPTZ,
    
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Indexes for design_files
CREATE INDEX idx_design_files_artist ON design_files(artist_id);
CREATE INDEX idx_design_files_format ON design_files(format);

-- Comments
COMMENT ON TABLE design_files IS 'Uploaded design assets by artists';
COMMENT ON COLUMN design_files.dominant_colors IS 'Array of dominant colors with hex values and percentages';

-- =============================================
-- 4. GARMENT MODELS - 3D model assets
-- =============================================
CREATE TABLE garment_models (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    
    -- Model info
    type TEXT NOT NULL CHECK (type IN ('tshirt', 'hoodie', 'tank', 'longsleeve', 'sweatpants', 'shorts')),
    variant_id TEXT NOT NULL,
    name TEXT NOT NULL,
    
    -- Storage
    model_url TEXT NOT NULL, -- GLTF/GLB file
    texture_url TEXT, -- Optional texture atlas
    
    -- Technical specs
    polygon_count INTEGER,
    has_lods BOOLEAN DEFAULT false, -- Level of Detail variants
    file_size_bytes INTEGER,
    
    -- UV mapping data
    uv_regions JSONB, -- { "chest": { "u": [0.2, 0.8], "v": [0.3, 0.7] }, ... }
    print_areas JSONB, -- Valid print area definitions
    
    -- Status
    is_active BOOLEAN DEFAULT true,
    version INTEGER DEFAULT 1,
    
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Indexes for garment_models
CREATE INDEX idx_garment_models_type ON garment_models(type);
CREATE INDEX idx_garment_models_active ON garment_models(is_active) WHERE is_active = true;
CREATE INDEX idx_garment_models_type_variant ON garment_models(type, variant_id);

-- Unique constraint to prevent duplicate variants
CREATE UNIQUE INDEX idx_garment_models_unique_variant 
    ON garment_models(type, variant_id) 
    WHERE is_active = true;

-- Comments
COMMENT ON TABLE garment_models IS '3D garment model assets for mockup rendering';
COMMENT ON COLUMN garment_models.uv_regions IS 'UV coordinate regions for different garment areas';
COMMENT ON COLUMN garment_models.print_areas IS 'Valid print area definitions for design placement';
COMMENT ON COLUMN garment_models.has_lods IS 'Whether model has Level of Detail variants for performance';

-- =============================================
-- 5. ROW LEVEL SECURITY POLICIES
-- =============================================

-- Enable RLS on all tables
ALTER TABLE mockup_presets ENABLE ROW LEVEL SECURITY;
ALTER TABLE mockup_renders ENABLE ROW LEVEL SECURITY;
ALTER TABLE design_files ENABLE ROW LEVEL SECURITY;
ALTER TABLE garment_models ENABLE ROW LEVEL SECURITY;

-- Artists can CRUD their own presets
CREATE POLICY "Artists can manage own presets" ON mockup_presets
    FOR ALL USING (artist_id = auth.uid());

-- Public presets are readable by all
CREATE POLICY "Public presets are readable" ON mockup_presets
    FOR SELECT USING (is_public = true);

-- Artists can manage own design files
CREATE POLICY "Artists can manage own designs" ON design_files
    FOR ALL USING (artist_id = auth.uid());

-- Renders inherit preset permissions
CREATE POLICY "Renders follow preset permissions" ON mockup_renders
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM mockup_presets 
            WHERE mockup_presets.id = mockup_renders.preset_id
            AND (mockup_presets.artist_id = auth.uid() OR mockup_presets.is_public = true)
        )
    );

-- Artists can manage renders of their own presets
CREATE POLICY "Artists can manage own renders" ON mockup_renders
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM mockup_presets 
            WHERE mockup_presets.id = mockup_renders.preset_id
            AND mockup_presets.artist_id = auth.uid()
        )
    );

-- Models are readable by all authenticated users
CREATE POLICY "Models readable by authenticated" ON garment_models
    FOR SELECT USING (auth.role() = 'authenticated');

-- Only admins can modify garment models (requires admin role check)
CREATE POLICY "Only admins can modify models" ON garment_models
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM profiles
            WHERE profiles.id = auth.uid()
            AND profiles.role = 'admin'
        )
    );

-- =============================================
-- 6. FUNCTIONS & TRIGGERS
-- =============================================

-- Update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_mockup_presets_updated_at
    BEFORE UPDATE ON mockup_presets
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- Increment usage count when preset is used
CREATE OR REPLACE FUNCTION increment_preset_usage()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE mockup_presets 
    SET usage_count = usage_count + 1, last_used_at = now()
    WHERE id = NEW.preset_id;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER on_render_created
    AFTER INSERT ON mockup_renders
    FOR EACH ROW EXECUTE FUNCTION increment_preset_usage();

-- Increment design file usage
CREATE OR REPLACE FUNCTION increment_design_usage()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE design_files 
    SET usage_count = usage_count + 1, last_used_at = now()
    WHERE id = NEW.design_file_id;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER on_preset_uses_design
    AFTER INSERT OR UPDATE OF design_file_id ON mockup_presets
    FOR EACH ROW 
    WHEN (NEW.design_file_id IS NOT NULL)
    EXECUTE FUNCTION increment_design_usage();

-- Get artist's preset stats
CREATE OR REPLACE FUNCTION get_artist_mockup_stats(artist_uuid UUID)
RETURNS TABLE (
    total_presets BIGINT,
    total_renders BIGINT,
    public_presets BIGINT,
    most_used_preset TEXT,
    storage_used_bytes BIGINT
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        COUNT(DISTINCT mp.id) as total_presets,
        COUNT(DISTINCT mr.id) as total_renders,
        COUNT(DISTINCT mp.id) FILTER (WHERE mp.is_public) as public_presets,
        (SELECT name FROM mockup_presets WHERE artist_id = artist_uuid ORDER BY usage_count DESC LIMIT 1) as most_used_preset,
        COALESCE(SUM(df.file_size_bytes), 0) + COALESCE(SUM(mr.file_size_bytes), 0) as storage_used_bytes
    FROM mockup_presets mp
    LEFT JOIN mockup_renders mr ON mr.preset_id = mp.id
    LEFT JOIN design_files df ON df.artist_id = mp.artist_id
    WHERE mp.artist_id = artist_uuid;
END;
$$ LANGUAGE plpgsql;

-- Search presets by name or tags
CREATE OR REPLACE FUNCTION search_mockup_presets(
    search_query TEXT,
    garment_filter TEXT DEFAULT NULL
)
RETURNS TABLE (
    id UUID,
    name TEXT,
    description TEXT,
    garment_type TEXT,
    is_public BOOLEAN,
    artist_id UUID,
    rank real
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        mp.id,
        mp.name,
        mp.description,
        mp.garment_type,
        mp.is_public,
        mp.artist_id,
        ts_rank(
            to_tsvector('english', coalesce(mp.name, '') || ' ' || coalesce(mp.description, '') || ' ' || coalesce(array_to_string(mp.tags, ' '), '')),
            plainto_tsquery('english', search_query)
        ) as rank
    FROM mockup_presets mp
    WHERE (
        to_tsvector('english', coalesce(mp.name, '') || ' ' || coalesce(mp.description, '') || ' ' || coalesce(array_to_string(mp.tags, ' '), ''))
        @@ plainto_tsquery('english', search_query)
        OR mp.name ILIKE '%' || search_query || '%'
    )
    AND (garment_filter IS NULL OR mp.garment_type = garment_filter)
    AND (mp.is_public = true OR mp.artist_id = auth.uid())
    ORDER BY rank DESC, mp.usage_count DESC;
END;
$$ LANGUAGE plpgsql;

-- =============================================
-- 7. STORAGE BUCKETS CONFIGURATION
-- =============================================

/*
Create the following storage buckets via Supabase dashboard or API:

1. designs
   - Purpose: Artist uploaded design files
   - Public: false (access via RLS)
   - File types: .png, .jpg, .webp
   - Max size: 10MB

2. mockups
   - Purpose: Rendered mockup images
   - Public: true (for shop listings)
   - File types: .png, .jpg, .webp
   - Max size: 5MB

3. garment-models
   - Purpose: 3D model files (GLTF/GLB)
   - Public: true (needed for 3D viewer)
   - File types: .gltf, .glb, .bin
   - Max size: 50MB

4. texture-atlases
   - Purpose: Generated texture atlases
   - Public: true (needed for rendering)
   - File types: .png, .jpg, .webp
   - Max size: 20MB

Storage RLS Policies:
---------------------

Bucket: designs
- INSERT: Artists can upload to their own folder (artist_id/*)
- SELECT: Artists can read their own files, public files readable by all
- DELETE: Artists can delete their own files
- UPDATE: Artists can update their own files

Bucket: mockups
- INSERT: System/Artists can upload (organized by artist_id/preset_id/)
- SELECT: Public mockups readable by all, private by owner only
- DELETE: Artists can delete their own mockups

Bucket: garment-models
- INSERT: Admin only
- SELECT: All authenticated users
- DELETE/UPDATE: Admin only

Bucket: texture-atlases
- INSERT: Admin only
- SELECT: All authenticated users
- DELETE/UPDATE: Admin only
*/

-- =============================================
-- 8. SEED DATA (Optional)
-- =============================================

-- Insert default garment models (run after creating the table)
/*
INSERT INTO garment_models (type, variant_id, name, model_url, uv_regions, print_areas) VALUES
('tshirt', 'classic-crew', 'Classic Crew Neck T-Shirt', 'garment-models/tshirt-classic.glb', 
 '{"chest": {"u": [0.25, 0.75], "v": [0.35, 0.75]}, "back": {"u": [0.25, 0.75], "v": [0.25, 0.65]}}',
 '["chest", "back", "left-sleeve", "right-sleeve"]'),
 
('hoodie', 'pullover', 'Pullover Hoodie', 'garment-models/hoodie-pullover.glb',
 '{"chest": {"u": [0.2, 0.8], "v": [0.3, 0.8]}, "back": {"u": [0.2, 0.8], "v": [0.2, 0.7]}}',
 '["chest", "back", "left-sleeve", "right-sleeve", "hood"]'),
 
('tank', 'muscle', 'Muscle Tank Top', 'garment-models/tank-muscle.glb',
 '{"chest": {"u": [0.25, 0.75], "v": [0.35, 0.75]}}',
 '["chest", "back"]'),
 
('longsleeve', 'classic', 'Long Sleeve T-Shirt', 'garment-models/longsleeve-classic.glb',
 '{"chest": {"u": [0.25, 0.75], "v": [0.35, 0.75]}, "left-sleeve": {"u": [0, 0.25], "v": [0.3, 0.8]}, "right-sleeve": {"u": [0.75, 1], "v": [0.3, 0.8]}}',
 '["chest", "back", "left-sleeve", "right-sleeve"]');
*/


-- ============================================
-- PERFORMANCE INDEXES
-- ============================================

-- Search indexes
CREATE INDEX IF NOT EXISTS idx_designs_tags_gin ON designs USING gin(tags);
CREATE INDEX IF NOT EXISTS idx_designs_style_tags_gin ON designs USING gin(style_tags);
CREATE INDEX IF NOT EXISTS idx_products_name_trgm ON products USING gin(name gin_trgm_ops);

-- Shop/catalog indexes
CREATE INDEX IF NOT EXISTS idx_product_designs_active ON product_designs(is_active) WHERE is_active = true;
CREATE INDEX IF NOT EXISTS idx_product_designs_artist ON product_designs(artist_id);
CREATE INDEX IF NOT EXISTS idx_product_designs_product ON product_designs(product_id);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_customer ON orders(customer_id);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_order_items_order ON order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_order_items_product_design ON order_items(product_design_id);

-- Partnership indexes
CREATE INDEX IF NOT EXISTS idx_partnership_codes_design ON partnership_codes(design_id);
CREATE INDEX IF NOT EXISTS idx_partnership_codes_artist ON partnership_codes(artist_id);
CREATE INDEX IF NOT EXISTS idx_design_partnerships_partner ON design_partnerships(partner_id);
CREATE INDEX IF NOT EXISTS idx_design_partnerships_design ON design_partnerships(design_id);
CREATE INDEX IF NOT EXISTS idx_garment_designs_product ON garment_designs(product_design_id);
CREATE INDEX IF NOT EXISTS idx_earnings_breakdown_recipient ON earnings_breakdown(recipient_id);
CREATE INDEX IF NOT EXISTS idx_earnings_breakdown_order_item ON earnings_breakdown(order_item_id);
CREATE INDEX IF NOT EXISTS idx_earnings_breakdown_payout ON earnings_breakdown(payout_id);
CREATE INDEX IF NOT EXISTS idx_deposit_recoup_payments_design ON deposit_recoup_payments(product_design_id);
CREATE INDEX IF NOT EXISTS idx_referral_earnings_referral ON referral_earnings(referral_id);
CREATE INDEX IF NOT EXISTS idx_referrals_referrer ON referrals(referrer_id);
CREATE INDEX IF NOT EXISTS idx_referrals_referred ON referrals(referred_artist_id);

-- Manufacturing indexes
CREATE INDEX IF NOT EXISTS idx_manufacturing_attempts_design ON manufacturing_attempts(product_design_id);
CREATE INDEX IF NOT EXISTS idx_manufacturing_quotes_design ON manufacturing_quotes(product_design_id);
CREATE INDEX IF NOT EXISTS idx_production_queue_design ON production_queue(product_design_id);

-- Mockup indexes
CREATE INDEX IF NOT EXISTS idx_mockup_presets_artist ON mockup_presets(artist_id);
CREATE INDEX IF NOT EXISTS idx_mockup_presets_garment ON mockup_presets(garment_type);
CREATE INDEX IF NOT EXISTS idx_mockup_renders_preset ON mockup_renders(preset_id);
CREATE INDEX IF NOT EXISTS idx_design_files_artist ON design_files(artist_id);
